version: '2.1'
services:
    zoo1:
        image: zookeeper
        restart: always
        ports:
            - 2181
    
    bookie1:
        image: caiok/bookkeeper:4.4.0
        restart: never
        ports:
            - 3181
        depends_on:
            - zoo1
        environment:
            ZK_SERVERS: zoo1:2181
            FORMAT_METADATA: "yes"
    
    bookie2:
        image: caiok/bookkeeper:4.4.0
        restart: never
        ports:
            - 3181
        depends_on:
            - zoo1
            - bookie1
        environment:
            ZK_SERVERS: zoo1:2181
    
    dice1:
        image: caiok/bookkeeper-tutorial
        restart: always
        depends_on:
            - zoo1
            - bookie1
            - bookie2
        environment:
            ZOOKEEPER_SERVERS: zoo1:2181
